import type { RuleSpec } from './ruleTypes'

export const RULES: RuleSpec[] = [
  {
    id: 'R-WALL-001',
    category: 'wall',
    title: '牌総数',
    status: 'implemented',
    summary: '進行中に物理牌の総数が破綻しないこと',
    testCases: ['createInitialGame', 'beginTurn', 'discardTile', 'playAutomaticTurn', 'declareReaction'],
  },
  {
    id: 'R-WALL-002',
    category: 'wall',
    title: '同種牌数',
    status: 'implemented',
    summary: '同じTileCodeの物理牌が5枚以上存在しないこと',
    testCases: ['validateGameState'],
  },
  {
    id: 'R-WALL-003',
    category: 'wall',
    title: '死牌保持',
    status: 'temporary',
    summary: '死牌14枚をdeadWallに保持し、通常ツモではまだ使用しない',
    testCases: ['createInitialGame', 'beginTurn'],
    notes: '将来のカン実装で嶺上牌管理に使う。',
  },
  {
    id: 'R-TURN-001',
    category: 'turn',
    title: 'ツモ',
    status: 'implemented',
    summary: '手番開始時、現在プレイヤーが牌山から1枚ツモる',
    testCases: ['beginTurn', 'playAutomaticTurn'],
  },
  {
    id: 'R-DISCARD-001',
    category: 'discard',
    title: '打牌',
    status: 'implemented',
    summary: '打牌時、手牌から1枚減り、河に1枚追加される',
    testCases: ['discardTile', 'discardHumanTile'],
  },
  {
    id: 'R-DISCARD-002',
    category: 'discard',
    title: '牌ID整合性',
    status: 'implemented',
    summary: 'drawnTileIdがある場合、その牌IDは現在プレイヤーの手牌に存在する',
    testCases: ['validateGameState'],
  },
  {
    id: 'R-RIICHI-001',
    category: 'riichi',
    title: 'リーチ後ツモ切り',
    status: 'implemented',
    summary: 'リーチ後はツモ牌以外を捨てられない',
    testCases: ['discardTile', 'autoDiscardRiichiDraw'],
  },
  {
    id: 'R-RIICHI-002',
    category: 'riichi',
    title: 'リーチ導線',
    status: 'implemented',
    summary: '基本条件を満たすなら、リーチ可能打牌が未確定でも宣言モードへ入れる',
    testCases: ['setRiichiDeclareMode', 'discardHumanTile', 'TableView'],
  },
  {
    id: 'R-CALL-001',
    category: 'call',
    title: 'チーは上家からのみ',
    status: 'implemented',
    summary: 'チーは上家の捨て牌に対してのみ可能',
    testCases: ['getChiOptions', 'declareReaction'],
  },
  {
    id: 'R-CALL-002',
    category: 'call',
    title: 'ポン',
    status: 'implemented',
    summary: '他家の捨て牌に対し、同種牌を2枚持っている場合に可能',
    testCases: ['getHumanReactionEvent', 'declareReaction'],
  },
  {
    id: 'R-CALL-003',
    category: 'call',
    title: 'ロン',
    status: 'implemented',
    summary: 'ロン可能な捨て牌に対してreaction_reviewに入る',
    testCases: ['discardTile', 'declareReaction'],
  },
  {
    id: 'R-CALL-004',
    category: 'call',
    title: '鳴きスキップ',
    status: 'implemented',
    summary: '鳴き確認をスキップした場合、通常進行へ戻る',
    testCases: ['skipReactionReview'],
  },
  {
    id: 'R-CALL-005',
    category: 'call',
    title: '鳴かれた捨て牌の二重カウント',
    status: 'implemented',
    summary: '鳴かれた捨て牌は物理牌検査で副露側だけを数える',
    testCases: ['validateGameState', 'declareReaction'],
  },
  {
    id: 'R-CALL-006',
    category: 'call',
    title: '相手番中の鳴き候補蓄積',
    status: 'implemented',
    summary: '下家・対面の鳴き候補は人間のツモ前境界まで、相手番内部状態をまたいで蓄積できる',
    testCases: ['discardTile', 'validateGameState'],
    notes: '通常麻雀ルールではなく、爆速麻雀の高速進行UIで相手番を止めすぎないための独自仕様。人間が選択できる段階ではreaction_reviewまたはdeclare_reactionに入る。',
  },
  {
    id: 'R-FURITEN-001',
    category: 'win',
    title: '捨て牌フリテン',
    status: 'implemented',
    summary: '自分の河に現在の待ち牌が含まれる場合、他家の捨て牌ではロンできない',
    testCases: ['getFuritenInfo', 'getHumanReactionEvent', 'declareReaction'],
    notes: 'ツモ和了は可能。',
  },
  {
    id: 'R-FURITEN-002',
    category: 'win',
    title: '一時フリテン',
    status: 'implemented',
    summary: 'ロン可能牌を見送った場合、次の自分のツモ番開始までロンできない',
    testCases: ['skipReactionReview', 'beginTurn', 'getFuritenInfo'],
    notes: '爆速麻雀のpendingReactionEvents蓄積仕様により、同一review内のロン候補見送りはreview以降のロン不可として扱う。',
  },
  {
    id: 'R-FURITEN-003',
    category: 'win',
    title: 'リーチ後見逃しフリテン',
    status: 'implemented',
    summary: 'リーチ後にロン可能牌を見送った場合、その局の終了までロンできない',
    testCases: ['skipReactionReview', 'getFuritenInfo', 'declareReaction'],
    notes: '今回の対象は他家捨て牌に対するロン見逃し。',
  },
  {
    id: 'R-FURITEN-004',
    category: 'win',
    title: 'ツモ和了',
    status: 'implemented',
    summary: 'フリテン中でもツモ和了は可能',
    testCases: ['canDeclareTsumo', 'declareWin'],
    notes: '現行のツモ和了UI仕様範囲ではリーチ中のツモ和了を確認対象とする。非リーチ時のツモ和了UI拡張は別タスク。',
  },
  {
    id: 'R-FURITEN-005',
    category: 'win',
    title: 'UI表示',
    status: 'implemented',
    summary: 'ロン可能だがフリテンで不可の場合、ユーザーに理由を表示する',
    testCases: ['TableView', 'ReactionEvent'],
  },
  {
    id: 'R-FURITEN-006',
    category: 'debug',
    title: 'ReactionEvent整合性',
    status: 'implemented',
    summary: 'rawCanRonとcanRonの差分をronBlockedReasonとfuritenInfoで説明する',
    testCases: ['validateGameState', 'getHumanReactionEvent'],
  },
  {
    id: 'R-KAN-001',
    category: 'kan',
    title: 'カン未対応',
    status: 'unsupported',
    summary: '現時点では暗槓・大明槓・加槓を宣言できない',
    testCases: ['reactionEvents', 'TableView', 'validateGameState'],
  },
  {
    id: 'R-KAN-002',
    category: 'kan',
    title: '将来対応: 嶺上牌',
    status: 'planned',
    summary: '将来カン実装時は、カン後に死牌側から嶺上牌をツモする',
    testCases: ['future-kan'],
  },
  {
    id: 'R-KAN-003',
    category: 'kan',
    title: '将来対応: 加槓と槍槓',
    status: 'planned',
    summary: '将来加槓を実装する場合、槍槓確認を挟む',
    testCases: ['future-kan'],
  },
  {
    id: 'R-DEBUG-001',
    category: 'debug',
    title: '状態検査',
    status: 'implemented',
    summary: '主要な状態遷移後にvalidateGameStateで重大な破綻を検出する',
    testCases: ['validateGameState'],
  },
  {
    id: 'R-DEBUG-002',
    category: 'debug',
    title: 'イベントログ',
    status: 'implemented',
    summary: '局進行をeventLogで追跡できる',
    testCases: ['eventLog'],
  },
]

export function getRuleById(id: string): RuleSpec | undefined {
  return RULES.find((rule) => rule.id === id)
}
